version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      RAILS_ENV: production
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - ./src:/myapp
      - public_data:/myapp/public
      - tmp_data:/myapp/tmp
      - log_data:/myapp/log
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - public_data:/myapp/public
      - tmp_data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public_data:
  tmp_data:
  log_data:
