# 将来的には対応する規約の読込
# inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # rubocopの検査事項を全て適用
  NewCops: enable
  # Rubyバージョン指定
  TargetRubyVersion: 2.7
  # チェック対象から除外するファイル
  Exclude:
    - "node_modules/**/*" # rubocop config/default.yml
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "config.ru"
    - "bin/**"
    - "lib/**"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config/**/*"
    - "script/**/*"
    - !ruby/regexp /old_and_unused\.rb$/

#################### Rails #################################
Rails:
  Enabled: true

#################### Style #################################
# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視
Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
